name: Test Action
on:
  push:
    branches: ["main"]

jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo hola mundo
      # - name: Checkout
      #   uses: actions/checkout@v4
      # - uses: actions/setup=node@v4
      #   with:
      #     node-version: 25
      #     cache: 'npm'
      # - name: Install packages
      #   run: pnpm ci
      # - name: Run ESlint
      #   run: pnpm run lint
      # - name: Build
      #   run: pnpm run build
